package Proyecto;


import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kike
 */
public class VtnP extends javax.swing.JFrame {

    /**
     * Creates new form VtnP
     */
    public VtnP() {
        initComponents();
        cargarTabla();
        llenarcombo();
    }

    public void cargarTabla() {

        DefaultTableModel modelotabla = (DefaultTableModel) Tablapaquete.getModel();
        modelotabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("Select* from paquete");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelotabla.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablapaquete = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtPaquete_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtAsunto = new javax.swing.JTextField();
        TxtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboTransporte = new javax.swing.JComboBox<>();
        jdt = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Borrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        Tablapaquete.setBackground(new java.awt.Color(0, 0, 0));
        Tablapaquete.setForeground(new java.awt.Color(255, 255, 255));
        Tablapaquete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Paquete ID", "Fecha de emision", "Cantidad", "Asunto", "Descripción", "Transporte"
            }
        ));
        Tablapaquete.setGridColor(new java.awt.Color(0, 0, 0));
        Tablapaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablapaqueteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablapaquete);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 540, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Paquetes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Paquete ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        TxtPaquete_id.setBackground(new java.awt.Color(0, 0, 0));
        TxtPaquete_id.setForeground(new java.awt.Color(255, 255, 255));
        TxtPaquete_id.setCaretColor(new java.awt.Color(255, 255, 255));
        TxtPaquete_id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtPaquete_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPaquete_idActionPerformed(evt);
            }
        });
        getContentPane().add(TxtPaquete_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 280, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de emision ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Asunto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        txtCantidad.setBackground(new java.awt.Color(0, 0, 0));
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 280, -1));

        txtAsunto.setBackground(new java.awt.Color(0, 0, 0));
        txtAsunto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 280, -1));

        TxtDescripcion.setBackground(new java.awt.Color(0, 0, 0));
        TxtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TxtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 280, 54));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripcion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        comboTransporte.setBackground(new java.awt.Color(0, 0, 0));
        comboTransporte.setForeground(new java.awt.Color(255, 255, 255));
        comboTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTransporteActionPerformed(evt);
            }
        });
        getContentPane().add(comboTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 280, -1));

        jdt.setBackground(new java.awt.Color(0, 0, 0));
        jdt.setForeground(new java.awt.Color(255, 255, 255));
        jdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdtKeyPressed(evt);
            }
        });
        getContentPane().add(jdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 280, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transporte ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\kike\\Documents\\NetBeansProjects\\Proyecto_base_de_datos\\Imagenes\\Interface.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void llenarcombo() {
//Creamos objeto tipo Connection    
        java.sql.Connection conectar = null;
        PreparedStatement pst = null;
        ResultSet result = null;

//Creamos la Consulta SQL
        String SSQL = "Select* from view_transporte";

//Establecemos bloque try-catch-finally
        try {

            //Establecemos conexión con la BD 
            Connection con = Conexion.getConexion();
            //Preparamos la consulta SQL
            pst = con.prepareStatement(SSQL);
            //Ejecutamos la consulta
            result = pst.executeQuery();

            //LLenamos nuestro ComboBox
            comboTransporte.addItem("Seleccione una opción");

            while (result.next()) {

                comboTransporte.addItem(result.getString("TRANSPORTE_ID"));

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e);

        } finally {

            if (conectar != null) {

                try {

                    conectar.close();
                    result.close();

                    conectar = null;
                    result = null;

               } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
      
      catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
            }

        }

    }
    private void comboTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTransporteActionPerformed

    private void TxtPaquete_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPaquete_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPaquete_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try {
       
       
       if (TxtDescripcion.getText().isEmpty() || TxtPaquete_id.getText().isEmpty() || txtAsunto.getText().isEmpty() || txtCantidad.getText().isEmpty() ) {
        JOptionPane.showMessageDialog(this, "Campos Vacios");
        
      
        }
  else{
        if(jdt.getDate() == null){
 JOptionPane.showMessageDialog(null, "fecha sin valores, por favor ingrese una fecha");

}
else{
     
       
            
               int paquete_id = Integer.parseInt(TxtPaquete_id.getText());
        String dia = Integer.toString(jdt.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jdt.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(jdt.getCalendar().get(Calendar.YEAR));
        String fecha_emision = (dia + "/" + mes + "/" + year);
        String asunto = txtAsunto.getText();
        String descripcion = TxtDescripcion.getText();
        int cantidad = Integer.parseInt(txtCantidad.getText());
        int transporte_id = Integer.parseInt(comboTransporte.getSelectedItem().toString());
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO paquete (PAQUETE_ID, FECHA_EMISION, CANTIDAD, ASUNTO, DESCRIPCION, TRANSPORTE_ID)VALUES(?,?,?,?,?,?)");
            ps.setInt(1, paquete_id);
            ps.setString(2, fecha_emision);
            ps.setInt(3, cantidad);
            ps.setString(4, asunto);
            ps.setString(5, descripcion);
            ps.setInt(6, transporte_id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro guardado");
            cargarTabla();

       
}} } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
    catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
   
   
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jdtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdtKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {

        }
    }//GEN-LAST:event_jdtKeyPressed

    private void TablapaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablapaqueteMouseClicked
        try {
            PreparedStatement ps;
            ResultSet rs;
            int fila = Tablapaquete.getSelectedRow();
            int id = Integer.parseInt(Tablapaquete.getValueAt(fila, 0).toString());
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("Select PAQUETE_ID, FECHA_EMISION, CANTIDAD, ASUNTO, DESCRIPCION, TRANSPORTE_ID from paquete where PAQUETE_ID=?");
            ps.setInt(1, id);
            rs = ps.executeQuery();

            while (rs.next()) {
                TxtPaquete_id.setText(String.valueOf(id));
                TxtDescripcion.setText(rs.getString("descripcion"));
                txtCantidad.setText(rs.getString("CANTIDAD"));
                txtAsunto.setText(rs.getString("CANTIDAD"));

                
                
                comboTransporte.setSelectedItem(rs.getString("TRANSPORTE_ID"));
   
                
            }

       } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
      
      catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());

        } 
    }//GEN-LAST:event_TablapaqueteMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try { if(jdt.getDate() == null){
 JOptionPane.showMessageDialog(null, "fecha sin valores, por favor ingrese una fecha");

}
else{
        int paquete_id = Integer.parseInt(TxtPaquete_id.getText());
        String dia = Integer.toString(jdt.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jdt.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(jdt.getCalendar().get(Calendar.YEAR));
        String fecha_emision = (dia + "/" + mes + "/" + year);
        String asunto = txtAsunto.getText();
        String descripcion = TxtDescripcion.getText();
        int cantidad = Integer.parseInt(txtCantidad.getText());
        int transporte_id = Integer.parseInt(comboTransporte.getSelectedItem().toString());
        
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("update  paquete set FECHA_EMISION=?, CANTIDAD=?, ASUNTO=?, DESCRIPCION=?, TRANSPORTE_ID=? where paquete_id=?");
           
            ps.setString(1, fecha_emision);
            ps.setInt(2, cantidad);
            ps.setString(3, asunto);
            ps.setString(4, descripcion);
            ps.setInt(5, transporte_id);
             ps.setInt(6, paquete_id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro guardado");
            cargarTabla();

       
} } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
      
      catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         try {  int paquete_id = Integer.parseInt(TxtPaquete_id.getText());
        
    
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("delete from paquete where paquete_id=?");
            
            
                ps.setInt(1, paquete_id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro borrado");
            cargarTabla();

       } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
      
      catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablapaquete;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JTextField TxtPaquete_id;
    private javax.swing.JComboBox<String> comboTransporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdt;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
