package Proyecto;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kike
 */
public class VtnT extends javax.swing.JFrame {

    /**
     * Creates new form VtnT
     */
    public VtnT() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTransporte = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Seguimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tipo = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ID_Transporte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Borrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        TablaTransporte.setBackground(new java.awt.Color(0, 0, 0));
        TablaTransporte.setForeground(new java.awt.Color(255, 255, 255));
        TablaTransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tranporte ID", "Descripción", "Tipo", "Seguimiento"
            }
        ));
        TablaTransporte.setGridColor(new java.awt.Color(0, 0, 102));
        TablaTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaTransporteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaTransporte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 510, 90));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Transporte");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, 20));

        Seguimiento.setBackground(new java.awt.Color(0, 0, 0));
        Seguimiento.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Seguimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 294, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seguimiento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 54, 10));

        Tipo.setBackground(new java.awt.Color(0, 0, 0));
        Tipo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 294, 26));

        Descripcion.setBackground(new java.awt.Color(0, 0, 0));
        Descripcion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 294, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  ID Transporte");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        ID_Transporte.setBackground(new java.awt.Color(0, 0, 0));
        ID_Transporte.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ID_Transporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 294, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\kike\\Documents\\NetBeansProjects\\Proyecto_base_de_datos\\Imagenes\\Interface.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {  String id_transporte = ID_Transporte.getText();
        String descripcion = Descripcion.getText();
        String tipo = Tipo.getText();
        String seguimiento = Seguimiento.getText();

       
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO transporte (TRANSPORTE_ID,descripcion,tipo,seguimiento)VALUES(?,?,?,?)");
            ps.setString(1, id_transporte);
            ps.setString(2, descripcion);
            ps.setString(3, tipo);
            ps.setString(4, seguimiento);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro guardado");
            cargarTabla();

       } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString(),"", JOptionPane.ERROR_MESSAGE);

        }
      
      catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TablaTransporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaTransporteMouseClicked
        try {
            PreparedStatement ps;
            ResultSet rs;
            int fila = TablaTransporte.getSelectedRow();
            int id = Integer.parseInt(TablaTransporte.getValueAt(fila, 0).toString());
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("Select TRANSPORTE_ID, descripcion,tipo,seguimiento from Transporte where TRANSPORTE_ID=?");
            ps.setInt(1, id);
            rs = ps.executeQuery();

            while (rs.next()) {
                ID_Transporte.setText(String.valueOf(id));
                Descripcion.setText(rs.getString("descripcion"));
                Tipo.setText(rs.getString("tipo"));
                Seguimiento.setText(rs.getString("seguimiento"));
                
            }

       } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString(),"", JOptionPane.ERROR_MESSAGE);

        }
      
      catch (Exception e) {
         JOptionPane.showMessageDialog(null, e.toString());

        }

    }//GEN-LAST:event_TablaTransporteMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          try {int transporte_id = Integer.parseInt(ID_Transporte.getText());
        String descripcion = Descripcion.getText();
        String tipo = Tipo.getText();
        String seguimiento = Seguimiento.getText();

      
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("update transporte set DESCRIPCION=?,TIPO=?, SEGUIMIENTO=? where transporte_id=?");
            
            ps.setString(1, descripcion);
            ps.setString(2, tipo);
            ps.setString(3, seguimiento);
                ps.setInt(4, transporte_id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Modificado");
            cargarTabla();

       } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e.toString(),"", JOptionPane.ERROR_MESSAGE);

        }
      
      catch (Exception e) {
          JOptionPane.showMessageDialog(null, e.toString());

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          try {int transporte_id = Integer.parseInt(ID_Transporte.getText());
        
     
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("delete from transporte where transporte_id=?");
            
            
                ps.setInt(1, transporte_id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro borrado");
            cargarTabla();

      } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e.toString(),"", JOptionPane.ERROR_MESSAGE);

        }
      
      catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    public void cargarTabla() {
 try {
        DefaultTableModel modelotabla = (DefaultTableModel) TablaTransporte.getModel();
        modelotabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
       
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("Select* from Transporte");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelotabla.addRow(fila);
            }

      } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e.toString(),"", JOptionPane.ERROR_MESSAGE);

        }
      
      catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField ID_Transporte;
    private javax.swing.JTextField Seguimiento;
    private javax.swing.JTable TablaTransporte;
    private javax.swing.JTextField Tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
